<?php if ($this->requirements->hasWarning()): ?>
    <h2><?php echo __('Installation Warning'); ?></h2>
    <p><?php echo __('The following issues will not affect installation, but they may negatively affect the behavior of Omeka:'); ?>'</p>
    <ol>
    <?php foreach($this->requirements->getWarningMessages() as $warningMessage): ?>
        <li>
            <h3 class="warning"><?php echo $warningMessage['header']; ?></h3>
            <p><?php echo $warningMessage['message']; ?></p>
        </li>
    <?php endforeach; ?>
    </ol>
<?php endif; ?>
<h2><?php echo __('Configure Your Site'); ?> <span id="required-note">* <?php echo __('Required Fields'); ?></span></h2>
<?php if ($this->form->isErrors()): ?>
    <h3 class="validation-error"><?php echo __('Form Validation Errors'); ?></h3>
    <p><?php echo __('There were errors found in your form. Please edit and resubmit.'); ?></p>
<?php endif; ?>
<?php echo $this->form; /* Display the install form. */?>
