<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<title><?php echo __('Omeka Installation'); ?></title>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/screen.css')); ?>
</head>
<body>
<h1><?php echo __('Omeka Installation'); ?></h1>
<div id="content">
    <?php echo $this->layout()->content ?>
</div>
</body>
</html>