<?php
/**
 * ExhibitPageEntry
 * @package: Omeka
 */
class ExhibitPageEntry extends Omeka_Record
{
	public $item_id;
	public $page_id;
	public $text;
	public $order;
	
	protected $_related = array('Item'=>'getItem');

	protected function getItem()
	{
		return $this->getTable('Item')->find($this->item_id);
	}
	
	protected function _validate()
	{
		if(empty($this->page_id)) {
			$this->addError('page_id', "Must be associated with a page of an exhibit.");
		}
		
		if(empty($this->order)) {
			$this->addError('order', "Must be ordered on the exhibit page.");
		}
		
		if(!is_numeric($this->item_id) or !is_numeric($this->page_id) or !is_numeric($this->order)) {
			$this->addError(null, 'item_id, page_id and order fields must all have proper numeric input');
		}
	}
	
	/**
	 * Customized plugin hook.  Autogenerated hook fires as 'pre_delete_itemspages'
	 * which certainly doesn't make any damn sense to a plugin writer
	 *
	 * @return void
	 **/
/*
	protected function preDelete()
	{
		fire_plugin_hook('pre_delete_exhibit_page_entry', $this);
	}
	
	protected function postDelete()
	{
		fire_plugin_hook('post_delete_exhibit_page_entry', $this);
	}
	
	protected function preInsert()
	{
		fire_plugin_hook('pre_insert_exhibit_page_entry', $this);
	}
	
	protected function postInsert()
	{
		fire_plugin_hook('post_insert_exhibit_page_entry', $this);
	}	
*/	
}

?>