CREATE TABLE IF NOT EXISTS `%PREFIX%elements` (
  `id` int unsigned NOT NULL auto_increment,
  `element_set_id` int unsigned NOT NULL,
  `order` int unsigned default NULL,
  `name` varchar(255) collate utf8_unicode_ci NOT NULL,
  `description` text collate utf8_unicode_ci,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name_element_set_id` (`element_set_id`,`name`),
  UNIQUE KEY `order_element_set_id` (`element_set_id`,`order`),
  KEY `element_set_id` (`element_set_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `%PREFIX%elements` VALUES 
(1, 3, NULL, 'Text', 'Any textual data included in the document.'),
(2, 3, NULL, 'Interviewer', 'The person(s) performing the interview.'),
(3, 3, NULL, 'Interviewee', 'The person(s) being interviewed.'),
(4, 3, NULL, 'Location', 'The location of the interview.'),
(5, 3, NULL, 'Transcription', 'Any written text transcribed from a sound.'),
(6, 3, NULL, 'Local URL', 'The URL of the local directory containing all assets of the website.'),
(7, 3, NULL, 'Original Format', 'If the image is of an object, state the type of object, such as painting, sculpture, paper, photo, and additional data'),
(10, 3, NULL, 'Physical Dimensions', 'The actual physical size of the original image.'),
(11, 3, NULL, 'Duration', 'Length of time involved (seconds, minutes, hours, days, class periods, etc.)'),
(12, 3, NULL, 'Compression', 'Type/rate of compression for moving image file (i.e. MPEG-4)'),
(13, 3, NULL, 'Producer', 'Name (or names) of the person who produced the video.'),
(14, 3, NULL, 'Director', 'Name (or names) of the person who produced the video.'),
(15, 3, NULL, 'Bit Rate/Frequency', 'Rate at which bits are transferred (i.e. 96 kbit/s would be FM quality audio)'),
(16, 3, NULL, 'Time Summary', 'A summary of an interview given for different time stamps throughout the interview'),
(17, 3, NULL, 'Email Body', 'The main body of the email, including all replied and forwarded text and headers.'),
(18, 3, NULL, 'Subject Line', 'The content of the subject line of the email.'),
(19, 3, NULL, 'From', 'The name and email address of the person sending the email.'),
(20, 3, NULL, 'To', 'The name(s) and email address(es) of the person to whom the email was sent.'),
(21, 3, NULL, 'CC', 'The name(s) and email address(es) of the person to whom the email was carbon copied.'),
(22, 3, NULL, 'BCC', 'The name(s) and email address(es) of the person to whom the email was blind carbon copied.'),
(23, 3, NULL, 'Number of Attachments', 'The number of attachments to the email.'),
(24, 3, NULL, 'Standards', ''),
(25, 3, NULL, 'Objectives', ''),
(26, 3, NULL, 'Materials', ''),
(27, 3, NULL, 'Lesson Plan Text', ''),
(28, 3, NULL, 'URL', ''),
(29, 3, NULL, 'Event Type', ''),
(30, 3, NULL, 'Participants', 'Names of individuals or groups participating in the event.'),
(31, 3, NULL, 'Birth Date', ''),
(32, 3, NULL, 'Birthplace', ''),
(33, 3, NULL, 'Death Date', ''),
(34, 3, NULL, 'Occupation', ''),
(35, 3, NULL, 'Biographical Text', ''),
(36, 3, NULL, 'Bibliography', ''),
(37, 1, 8, 'Contributor', 'An entity responsible for making contributions to the resource.'),
(38, 1, 15, 'Coverage', 'The spatial or temporal topic of the resource, the spatial applicability of the resource, or the jurisdiction under which the resource is relevant.'),
(39, 1, 4, 'Creator', 'An entity primarily responsible for making the resource.'),
(40, 1, 7, 'Date', 'A point or period of time associated with an event in the lifecycle of the resource.'),
(41, 1, 3, 'Description', 'An account of the resource.'),
(42, 1, 11, 'Format', 'The file format, physical medium, or dimensions of the resource.'),
(43, 1, 14, 'Identifier', 'An unambiguous reference to the resource within a given context.'),
(44, 1, 12, 'Language', 'A language of the resource.'),
(45, 1, 6, 'Publisher', 'An entity responsible for making the resource available.'),
(46, 1, 10, 'Relation', 'A related resource.'),
(47, 1, 9, 'Rights', 'Information about rights held in and over the resource.'),
(48, 1, 5, 'Source', 'A related resource from which the described resource is derived.'),
(49, 1, 2, 'Subject', 'The topic of the resource.'),
(50, 1, 1, 'Title', 'A name given to the resource.'),
(51, 1, 13, 'Type', 'The nature or genre of the resource.'),
(58, 4, 1, 'Additional Creator', ''),
(59, 4, 2, 'Transcriber', ''),
(60, 4, 3, 'Producer', ''),
(61, 4, 4, 'Render Device', ''),
(62, 4, 5, 'Render Details', ''),
(63, 4, 6, 'Capture Date', ''),
(64, 4, 7, 'Capture Device', ''),
(65, 4, 8, 'Capture Details', ''),
(66, 4, 9, 'Change History', ''),
(67, 4, 10, 'Watermark', ''),
(69, 4, 12, 'Encryption', ''),
(70, 4, 13, 'Compression', ''),
(71, 4, 14, 'Post Processing', ''),
(72, 5, 1, 'Width', ''),
(73, 5, 2, 'Height', ''),
(74, 5, 3, 'Bit Depth', ''),
(75, 5, 4, 'Channels', ''),
(76, 5, 5, 'Exif String', ''),
(77, 5, 6, 'Exif Array', ''),
(78, 5, 7, 'IPTC String', ''),
(79, 5, 8, 'IPTC Array', ''),
(80, 6, 1, 'Bitrate', ''),
(81, 6, 2, 'Duration', ''),
(82, 6, 3, 'Sample Rate', ''),
(83, 6, 4, 'Codec', ''),
(84, 6, 5, 'Width', ''),
(85, 6, 6, 'Height', '');
