CREATE TABLE IF NOT EXISTS `%PREFIX%mime_element_set_lookup` (
  `id` int unsigned NOT NULL auto_increment,
  `element_set_id` int unsigned NOT NULL,
  `mime` varchar(255) collate utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `mime` (`mime`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `%PREFIX%mime_element_set_lookup` VALUES 
(1, 5, 'image/bmp'),
(2, 5, 'image/gif'),
(3, 5, 'image/ief'),
(4, 5, 'image/jpeg'),
(5, 5, 'image/pict'),
(6, 5, 'image/pjpeg'),
(7, 5, 'image/png'),
(8, 5, 'image/tiff'),
(9, 5, 'image/vnd.rn-realflash'),
(10, 5, 'image/vnd.rn-realpix'),
(11, 5, 'image/vnd.wap.wbmp'),
(12, 5, 'image/x-icon'),
(13, 5, 'image/x-jg'),
(14, 5, 'image/x-jps'),
(15, 5, 'image/x-niff'),
(16, 5, 'image/x-pcx'),
(17, 5, 'image/x-pict'),
(18, 5, 'image/x-quicktime'),
(19, 5, 'image/x-rgb'),
(20, 5, 'image/x-tiff'),
(21, 5, 'image/x-windows-bmp'),
(22, 5, 'image/x-xbitmap'),
(23, 5, 'image/x-xbm'),
(24, 5, 'image/x-xpixmap'),
(25, 5, 'image/x-xwd'),
(26, 5, 'image/x-xwindowdump'),
(27, 6, 'video/x-msvideo'),
(28, 6, 'video/avi'),
(29, 6, 'video/msvideo'),
(30, 6, 'video/x-mpeg'),
(31, 6, 'video/x-ms-asf'),
(32, 6, 'video/mpeg'),
(33, 6, 'video/quicktime'),
(34, 6, 'video/x-ms-wmv');
